name: 📚 Documentation
description: Report an issue or suggest an improvement in documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation! Clear documentation is crucial for our project's success.

  - type: dropdown
    id: type
    attributes:
      label: 📝 Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing Documentation
        - Incorrect Information
        - Unclear Explanation
        - Outdated Content
        - Example Needed
        - Typo/Grammar
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: 📍 Location
      description: Where is the documentation issue? (URL, file path, etc.)
      placeholder: e.g., /docs/getting-started.md or https://github.com/.../README.md
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: 📄 Current State
      description: What does the current documentation say? (if applicable)
      placeholder: Copy the relevant section or describe what exists now...

  - type: textarea
    id: desired
    attributes:
      label: ✨ Desired State
      description: How should the documentation be improved?
      placeholder: |
        Describe what you'd like to see:
        - Specific changes needed
        - Additional topics to cover
        - Examples to include
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: 👥 Target Audience
      description: Who is the primary audience for this documentation?
      options:
        - New Users
        - Experienced Users
        - Contributors
        - API Users
        - All Users
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 🔍 Additional Context
      description: Any other context that might help us understand the issue better?
      placeholder: |
        - Why is this change important?
        - What confusion did you experience?
        - Related documentation pages?

  - type: textarea
    id: proposal
    attributes:
      label: 📝 Proposed Changes
      description: If you have specific wording in mind, share it here
      placeholder: |
        ```markdown
        ## New Section Title

        Your proposed documentation text here...
        ```

  - type: checkboxes
    id: terms
    attributes:
      label: 🤝 Code of Conduct
      description: By submitting this documentation issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true 